version: "3.9" # specify docker-compose version

services:      # services to run
  app:         # name of the service
    build:     # build the image using the Dockerfile in the current directory
      context: .   # use the current directory. here '.' means the current directory
      args:
        - DEV=true # pass the DEV environment variable to the Dockerfile
    ports:
      - "8000:8000" # maps port 8000 on the host to port 8000 on the container
    volumes:
      - ./app:/app # maps the app directory in the host to the /app directory in the container
                   # this is used to share the code between the host and the container and to reflect the changes in the code without rebuilding the image
    command: >     # run the command to start the serve
      sh -c "python manage.py runserver 0.0.0.0:8000"